antfu-collective/vite-ssg

- README.md
* Vue router must be version 4.
* @vueuse/head is required.
> fix: rewrite install packages

- src/node/build.ts
I think can pick the first script tag of type module as the entry. fixes #27 
But I found another problem.
https://github.com/antfu/vite-ssg/blob/7fdbd7fa31122dd9149880e606b6f85db30a0bf1/src/node/build.ts#L74-L76
If the entry is `./src/main2.ts`, the code of line 75 will throw an error. Because the bundle build via vite are `main2.js`.
```sh
[vite-ssg] Build for server...
vite v2.2.3 building SSR bundle for production...
✓ 15 modules transformed.
.vite-ssg-temp/main2.js                    9.04kb
.vite-ssg-temp/assets/style.9cd99f46.css   0.14kb
Error: Cannot find module 'D:\code\vite-ssg\examples\multiple-pages\.vite-ssg-temp\main.js'
Require stack:
- D:\code\vite-ssg\dist\node\cli.js
```
I tried to extract the entry file of `createApp` with regex, but I don't think it's a good idea.
>  feat: entry auto detection

- src/utils/state.ts
It was SSR in vite-ssr, but I think it should be SSG here 😅
> Rename error prefix

- src/node/build.ts
- src/types.ts
fix https://github.com/antfu/vite-ssg/issues/70
> feat: pass the mode to vite

- src/client/index.ts
- src/node/build.ts
- src/types.ts
see some context to this [here](https://github.com/antfu/vite-ssg/issues/63)
This is either something very useful, or something very silly and I missed a point. Either way will be a good discussion.
Thanks
> feat: add routePath to SSG context

- src/node/build.ts
add abssolute path support to outDir
> feat: add absolute path support to outDir

- src/node/build.ts
This resolves #72. The issue is explained and discussed in detail there. I have used the solution proposed bu @userquin for last two weeks and it works great. 
Can this please be merged, as this issue has been there for a long time.
> fix: InitialState not updated for subsequent routes

- src/client/components/ClientOnly.ts
- src/client/index.ts
PR for https://github.com/antfu/vite-ssg/issues/116
> fix: client-side hydration & ClientOnly components.

- src/node/build.ts
- src/types.ts
Addresses https://github.com/antfu/vite-ssg/issues/165
> fix: remove appHTML transformation in triggerOnSSRAppRendered cb

- README.md
@antfu update also the **About** entry on the repo, I will also change it on vitesse template: I also update here the license to include`PRESENT`.
closes #185
> docs: update SSG acronym

- src/node/build.ts
- src/types.ts
The main problem here is we cannot connect client and server configuration and so we need to add `rootContainerId` to `ssgOptions`.
closes #52
> fix: custom div id on build not working

- README.md
- examples/README.md
Spent some time trying to run the examples, I think these doc changes can help the next person trying to do that. Please let me know if this is ok or if it need any other changes
> docs: minor documentation improvements

- src/index.ts
- src/node/index.ts
Export `build` function just like `vite`, I think this is useful when developers want to manage ssg manually.
> feat: export build from node/build.ts

- src/node/build.ts
- allow user pass vite inlineConfig for build
close #226
> feat: allow pass vite inlineConfig for build

- src/node/build.ts
When I set up some plugins, I had to merge my config.
> feat: merge viteConfig for build

- package.json
- pnpm-lock.yaml
- src/node/build.ts
- src/types.ts
This will prevent going out of memory in larger project
related #210
> Use queue for pages processing

- CONTRIBUTING.md
- README.md
- package.json
This PR includes:
- included `packageManager` on `package.json`
- added `Contribution` entry on `README.md`
- added `CONTRIBUTING.md`
> workflow: update to pnpm 7

- src/client/index.ts
> fix: router.push shouldn't contain base url

- README.md
> docs: fix markdown rendering

- package.json
In Single Page SSG, vue-router is not required.
> fix: set `vue-router` to optional

- src/types.ts
> chore: fix typos

- README.md
- src/node/build.ts
- src/node/cli.ts
- src/types.ts
This PR does the following:
- fixes some typos. I also took the liberty to rephrase some things (for increased clarity - from my pov). Let me know if I took it too far.
- resolves #111 and resolves #236
> feat: add cli option to specify vite config file

- package.json
- pnpm-lock.yaml
Updates @vueuse/head to latest
#298
👌
> chore: update @vueuse/head to 0.9.7

- README.md
This PR documents how to pass configuration into `critters`. This documents the response from #88.
> docs: document how to configure critters

- README.md
- package.json
- pnpm-lock.yaml
- src/node/build.ts
drop `@vueuse/head` 0.x
closes #298, closes #155
**BREAKING CHANGE**
> feat!: support vueuse head v1

- src/node/cli.ts
Solves https://github.com/antfu/vite-ssg/issues/339
I hope this PR enables the behavior seen on vite
> feat: exposing the --base argument

- README.md
@unhead/vue' docs link has been changed
> docs: bad link

- src/client/index.ts
- src/client/single-page.ts
- src/node/build.ts
> feat: use `import.meta.env.SSR`

- src/client/index.ts
- src/client/single-page.ts
- src/node/build.ts
Check linked issue
closes #441
> fix: use client/server createHead

- src/client/index.ts
We only need to await router ready on SSR not in client.
Check from comment https://github.com/antfu-collective/vite-ssg/pull/442#issuecomment-2763313385
closes #446
> fix: client router regression
