- README.md
- package.json
- src/build.ts
- tsconfig.json
#4 Change esbuild target to es2020 and add a notation on README.
> fix!: import.meta not supported, drop support of Node<14

- src/node/build.ts
- src/node/utils.ts
Hey, this is something I've been using with my website for a while now,
but I thought this could benefit others too.
Currently Vite-ssg only considers top-level routes, I've added a function that recursively traverses the route tree.
Since I've been using this myself for a while now, I'm quite confident that it does not introduce any errors but you might wanna have a closer look :)
Cheers!
> feat: support nested routes

- src/node/build.ts
- src/node/cli.ts
Because it was overridden by cli default values.
This PR also fixes some issues with options. (See commit message for details.)
> fix: config was not applied

- src/client/index.ts
- src/client/single-page.ts
- src/node/build.ts
- src/types.ts
Sometimes it can be useful to disable `@vueuse/head`. Especially for single-page website.
```js
export const createApp = ViteSSG(App, () => {}, {
registerComponents: false,
useHead: false
})
```
> feat: option to disable @vueuse/head

- src/client/index.ts
- src/client/single-page.ts
- src/types.ts
adds `rootContainer` option, defaulting to "#app", to let users specify where to mount the app.
fixes #38
> feat: add rootContainer option for app.mount

- src/node/utils.ts
fixes #44
Currently, a route with `prefix` will always strip the leading `/` and append the route to the prefix. After the change, only a route without a leading `/` would be concatenated with `prefix`. If the route has a leading `/` (prefix or not) the path will be taken verbatim.
> fix: children with leading / at root level

- src/node/build.ts
`url options` is required in jsdom constructor when using `localStorage` or `sessionStorage`.
Otherwise building will fail by `[DOMException [SecurityError]: localStorage is not available for opaque origins]`
[Relative Issue](https://github.com/jsdom/jsdom/issues/2304#issuecomment-408320484)
> fix: using localStorage(sessionStorage) and timer function in vue sfc will block building

- src/node/build.ts
When having `resolve.alias`, it failed to auto detect entry. refs #41 
```ts
export default defineConfig({
resolve: {
alias: {
'/@': 'something'
}
}
})
```
This PR resolves entry with `resolve.alias`.
Also passing `--entry /@/main.ts` will work.
> feat: support alias with entry

- package.json
- src/node/build.ts
- change file ending of temp file to .cjs if nearest package.json has type "module" set (fix: #61)
> fix: missing handling of type "module" in package.json

- src/node/build.ts
- src/types.ts
When you use nginx to deploy a static website, nginx will look for the index.html file under $URI, so add the useindexmode option to generate the corresponding path
Recommended for use with [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages)
for example:
```
routes =   [
{
name: 'index',
path: '/',
component: [Function: component],
props: true
},
{
name: 'list-card',
path: '/list/card',
component: [Function: component],
props: true
},
{
name: 'user',
path: '/user',
component: [Function: component],
props: true
},
{
name: 'user-id',
path: '/user/:id',
component: [Function: component],
props: true
}
]
```
build after :
```
...
~dist/index.html,
~dist/list/card/index.html,
~dist/user/index.html
~dist/user/:id/index.html
```
With nginx vhost, dynamic routing of static pages can …
> feat: support dirStyle and includeAllRoutes options

- src/client/index.ts
When adding router guards in modules (that are loaded in the fn argument) I expected that when entering a page (not by navigation but by typing in the url) the route would execute the guard, but it does not.
To remedy the guards should be set on the router before registering with vue.
> fix: install router after user setup

- src/node/build.ts
- src/types.ts
This is required to successfully prerender apps using the [NaiveUI](https://www.naiveui.com/) component library.
I will provide an example config here soon.
Closes #124
> feat: pass context to user application, close #124

- bin/vite-ssg.js
- package.json
- pnpm-lock.yaml
- src/node/build.ts
- src/node/cli.ts
- src/node/critical.ts
- src/node/jsdomGlobal.js
- tsup.config.ts
> Thank you for making `vite-ssg`! It's like magic! 
> It's only issue right now for me is with ESM-only dependencies.
> I hope this PR will help to move things forward with ESM.
Make `vite-ssg` work with ESM. Build format switched from `'cjs'` to `'esm'`.
Addresses: https://github.com/antfu/vite-ssg/issues/145
<br><hr>
**On another note:**
Usage of **jsdom** could also be improved: https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global
> feat: migrate to ESM

- bin/vite-ssg.js
- build.config.ts
- examples/multiple-pages-pwa/package.json
- examples/multiple-pages-with-store/package.json
- examples/multiple-pages/package.json
- examples/single-page/package.json
- package.json
- pnpm-lock.yaml
- src/node/build.ts
- src/node/cli.ts
- src/node/utils.ts
This PR includes:
- use `unbuild` instead `tsup`
- updated `package.json` to include types and change `js` extension with `cjs` extension; added also `sideEffect: false`.
- modified `single-page` and `multiple-pages-with-store` examples: we need to enable `cjs` format since it seems `vue-demi` is not `esm` compliant (the error comes from `pinia.mjs`, see below).
- modified `vite-ssg` binary to load `cjs` (via `require`) or `esm` (via `dynamic import`) module checking for `__dirname`.
- included regenerate `pwa`  if `disabled api`  option is false (option included on `v0.11.12`).
- using `kolorist` instead `chalk`
- updated all dependencies  to major
Error when building `single-page` with `esm`:
```shell
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none …
```
> feat: move to unbuild

- README.md
- src/node/build.ts
- src/types.ts
Suggestion to pass original route records to `includedRoutes` to allow for construction of dynamic paths without having to parse path strings.
> feat: pass original routes to includedRoutes cb

- src/node/build.ts
If the `index.html` is modified in the part of `<div id="app"></div>`, `vite-ssg` will not modify the HTML read from `index.html` before outputting it. All server-side rendering was for nothing in this case.
In #118 examples were discussed, where this actually happened.
This PR does not solve the issue by providing a robust way of identifying *the div with the id "app"*, but instead at least notifies the user what went wrong.
In a later PR this could be fixed properly.
My proposal would be to parse and tokenize the HTML with an html parser and get the position of the div in the file by working with the index.html's abstract syntax tree **if `<div id="app"></div>` cannot be found as string**. But that's a topic for another PR.
> feat: throw if <div id="app"></div> is absent

- package.json
- src/node/build.ts
As discussed in #118, adding a class to `<div id="app"></div>` will break rendering.
In #183 an error is thrown, if e. g. a class is added to the div, so the user gets notified he should not do that, but the problem still persists.
This PR aims to solve this.
The implementation:
* adds [html5Parser](https://www.npmjs.com/package/html5parser) as dependency for parsing html (I am open to use another parser, this one seemed to be fast and [small](https://bundlephobia.com/package/html5parser), I could not find an API for an AST with line numbers in the original string html with JSDOM)
* imports parser, parses html and walks ast **only if string div id="app" could not be found**
* inserts in first match of id="app" the rendered content
* leaves attributes on match untouched, only adds …
> feat: finds id="app" using parser as fallback

- package.json
- scripts/copy-single-page-dts.ts
* remove copy types script
* use [`typesVersions`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions) declaration in package.json to tell TS where to find correct typings location instead
Used `typesVersions` declaration:
```json
"typesVersions": {
"*": {
"single-page": ["dist/client/single-page.d.ts"]
}
},
```
Fixes #187
> fix: reference types correctly for single-page mode

- README.md
- src/node/build.ts
Adds support for specifying `includedRoutes` from server entry file. Support for specifying this from the config has been maintained - there are just two ways of supplying this information now.
Reasoning: it is difficult to perform more complex data fetching from inside the config file. This is primarily due to the fact that data fetching often makes use of sensitive keys and the main place one puts this kind of configuration is in the env config. Vite has a documented convention for env management which makes management of things like API keys nice and secure, but we cannot benefit from any of this from inside the vite config file, as the config file runs before the environment has been populated. Consider the following:
```javascript
async function includedRoutes(paths, routes) {
return …
```
> feat: support specifying included routes in server entry file

- README.md
Now the `next` tag is not necessary
> Use the default version for the router

- src/node/critical.ts
The `fs` module is imported as ES module since [critters-0.0.16](https://github.com/GoogleChromeLabs/critters/commit/46f983fbed18f19a3679aa39029bb6ec4df44956). Time to drop this workaround.
Related commit: https://github.com/GoogleChromeLabs/critters/commit/ec6e1443a75e915e81f4e4ee423cb149c2ae1f50
> refactor: remove critters fs import workaround

- package.json
I can not get type by `vite-ssg/node`.
When i add `"node": ["dist/node.d.ts"]`, it works.
> fix: export node type

- src/node/build.ts
tested on https://github.com/userquin/vite-ssg-esm-cli-150 with `mock` and `cjs` and https://github.com/userquin/vite-ssg-build-v-client-master with `mock`
fix #230
fix #51
fix #254
> fix: load jsdom before SSR build

- src/node/utils.ts
There was a previous attempt to fix this (https://github.com/antfu/vite-ssg/pull/91) but there are remaining broken cases. When routes have an empty path, their children are not processed, causing nested routes to be missed and remain unprefixed.
```javascript
//Previous implementation
console.log(routesToPaths([
{
path: '/foo',
children: [{path: '', children: [{ path: 'bar' }, {path: '/bar'}] }]
}
]))
//outputs [ '/foo', 'bar', '/bar' ] - incorrect
//With this PR
console.log(routesToPaths([
{
path: '/foo',
children: [{path: '', children: [{ path: 'bar' }, {path: '/bar'}] }]
}
]))
//outputs [ '/foo', '/foo/bar', '/bar' ]
```
> fix: nested routes when parent path is empty

- README.md
- src/client/components/ClientOnly.ts
- src/client/index.ts
- src/client/single-page.ts
Add `placeholder` slot for `<ClientOnly />`.
#281 
This change passed my local test.
> feat: add placeholder slot for <ClientOnly />

- src/node/build.ts
When running multiple vite-ssg instances at the same time, the build will fail due to the same ssgOut directory.
> feat: randomize `ssgOut` directory name

- src/node/build.ts
vite [recently changed](https://github.com/vitejs/vite/pull/10996/files#diff-11e17761d4ecfee8f8fde15c6d79b7bc0260176396a30dfd8e6f6bbaf5af4745R385) the signature for `resolveConfig()` to take a 4th argument `defaultNodeEnv`, which [by default is set to `development`](https://github.com/vitejs/vite/pull/10996/files#diff-11e17761d4ecfee8f8fde15c6d79b7bc0260176396a30dfd8e6f6bbaf5af4745R376).
Since this argument is not added [when `resolveConfig` is called](https://github.com/antfu/vite-ssg/blob/main/src/node/build.ts#L31) in vite-ssg, it causes [`NODE_ENV` to get set to `development`](https://github.com/vitejs/vite/pull/10996/files#diff-11e17761d4ecfee8f8fde15c6d79b7bc0260176396a30dfd8e6f6bbaf5af4745R385). 
n turn, this [triggers `vite-plugin-vue` to consider this a development …
> fix: absolute `__file` paths leaking into production bundle

- README.md
- examples/multiple-pages-pwa/package.json
- examples/multiple-pages-pwa/src/pages/b.vue
- examples/multiple-pages-pwa/src/pages/index.vue
- examples/multiple-pages-pwa/src/pages/nested/deep/a.vue
- examples/multiple-pages-with-store/package.json
- examples/multiple-pages-with-store/src/pages/b.vue
- examples/multiple-pages/package.json
- examples/multiple-pages/src/pages/b.vue
- examples/single-page/src/App.vue
- package.json
- pnpm-lock.yaml
- src/client/index.ts
- src/client/single-page.ts
- src/node/build.ts
- src/types.ts
Because `@vueuse/head` will be deprecated in the coming month, this PR replaces `@vueuse/head` with `@unhead/vue`.
https://github.com/vueuse/head#:~:text=%F0%9F%8C%87,installation%20guide.
This PR requires https://github.com/mdit-vue/vite-plugin-vue-markdown/pull/18 to be merged and released in advance.
> chore!: migrate to @unhead/vue from @vueuse/head

- src/node/build.ts
Add-on to #356 which fixed part of the problem, but building in alternate modes can still cause the issue. For example:
```
vite-ssg build --mode staging
```
Will correctly run a vite bundle in `staging` mode, but because of the issue detailed in #356 will also set `NODE_ENV` to `staging`, which [makes `vite-plugin-vue` think this is a development build](https://github.com/vitejs/vite-plugin-vue/blob/abdf5f4f32d02af641e5f60871bde14535569b1e/packages/plugin-vue/src/index.ts#L115) and leak `__file` paths.
If I understand correctly, `NODE_ENV` should really only ever be `production` or `development` (same as unset), so this PR sets the default `NODE_ENV` to `production` for any other `mode` except `development`.
(An alternate solution would be to do what vite does and set this to the …
> fix: absolute `__file` paths still leaking when building in alternate non-development modes

- examples/multiple-pages-pwa/src/main.ts
- examples/multiple-pages-with-store/src/main.ts
- examples/multiple-pages/.env
- examples/multiple-pages/.env.ssg
- examples/multiple-pages/package.json
- examples/multiple-pages/src/App.vue
- examples/multiple-pages/src/entry.ts
- src/node/build.ts
- src/types.ts
I noticed that vite-ssg build provides the `--base` option, but I found that it doesn't work as expected when I tried to use it.
Here are the tests I conducted after fixing this issue:
- Set `base` in vite.config.ts and perform a build to confirm the result.
- Set `ssgOptions.base` in vite.config.ts and perform a build to confirm the result.
- Add `--base` to vite-ssg build command and perform a build to confirm the result.
- Add `--mode` to vite-ssg build command and perform a build to confirm the result.
- Add both `--mode` and `--base` to vite-ssg build command and perform a build to confirm the result.
- Add `NODE_ENV` and `--mode` to vite-ssg build command and perform a build to confirm the result.
#339 #340 #341
> fix: the --base option not work

- examples/multiple-pages-pwa/package.json
- examples/multiple-pages-with-store/package.json
- examples/multiple-pages/package.json
- package.json
- pnpm-lock.yaml
Seems like something weird is going on with the version resolution where they are using a newer version of `@unhead/vue` but an older version of the `unhead` core.
I think this _should_ help.
Also, it seems like unhead went from an optional peer dependency to a strict dependency so I've updated that.
relates to #368, https://github.com/unjs/unhead/issues/230
> chore: bump unhead

- package.json
This change updates critters to version 0.0.20 in the peer dependencies section of the `package.json`. This is needed so that projects that are using vite-ssg can also update critters to version 0.0.20 in their dev dependencies.
This change also means that the same version of critters is now used in both the dev dependencies and peer dependencies of vite-ssg.
#119
#370
> fix: update critters peer dependency to version 0.0.20

- examples/single-page/src/App.vue
- src/node/build.ts
When <code>$\`</code> in `appHTML`, `indexHTML.replace` (renderHTML) will result in an abnormal replacement.
> [Specifying a string as the replacement | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement)
https://github.com/antfu/vite-ssg/blob/8015d55b798fa9d5f3ebb7c79763ec7ad429a795/src/node/build.ts#L279-L283
In order for it not to be affected by special rules, we need to convert it into a function.
```ts
() => `<div id="${rootContainerId}" data-server-rendered="true">${appHTML}</div>${stateScript}`
```
https://github.com/YunYouJun/valaxy/issues/295
It can be reproduced in the vite-ssg examples.
```html
<a href="https://github.com/antfu/vite-ssg" aria-label="Permalink to &quot;Usage `^`, …
```
> fix: renderHTML indexHTML.replace when appHTML with $

- src/node/build.ts
`join('file://')` will be equal to `'file:\'`, which is not the correct file protocol and will fail to be parsed under bun.
It is changed to '+' splicing here.
> fix: optimize the splicing method of serverEntry to make it compatible with bun

- package.json
- pnpm-lock.yaml
- src/node/build.ts
This PR replaces the vulnerable html-minifier package, which contained a CVE, with an updated html-minifier-terser package. I find this a good replacement since the html-minifier has not received any updates in 5 years.
#397 
Please do test the minifier, as I have no clue how to test that, I just replaced the deps and added an await
> feat: replace html-minifier with html-minifier-terser

- package.json
Because `^` does not mean a range for versions starting with `0.0`, the version of critters needs to be bumped. Otherwise, users will get incompatible versions error.
https://github.com/npm/node-semver/blob/main/README.md#caret-ranges-123-025-004:~:text=In%20other%20words%2C%20this%20allows%20patch%20and%20minor%20updates%20for%20versions%201.0.0%20and%20above%2C%20patch%20updates%20for%20versions%200.X%20%3E%3D0.1.0%2C%20and%20no%20updates%20for%20versions%200.0.X
refs #119, #380
> chore: update critters peerDep to 0.0.24

- src/node/build.ts
Remove the .vite-ssg-temp folder before and after a build, instead of removing just the randomly generated subfolder.
Closes #413 
Quality of Life improvement. This also removes any old folders where the previous build failed or was interrupted.
Please let me know if I need to modify anything.
> fix: remove the `.vite-ssg-temp` folder before and after a build

- package.json
See https://arethetypeswrong.github.io/?p=vite-ssg%400.24.1
Fix `🎭 Masquerading as CJS` issue
> fix: remove `types` field

- src/client/index.ts
- src/client/single-page.ts
- src/types.ts
Add `useHydrate` option to enable Vue hydration on client side.
- https://vuejs.org/guide/scaling-up/ssr.html#client-hydration
- https://vuejs.org/api/application.html#createssrapp
https://github.com/antfu-collective/vite-ssg/issues/410
Previous  PR: https://github.com/antfu-collective/vite-ssg/pull/432
> feat: support `hydration` option (#410)

- README.md
- eslint.config.mjs
- examples/multiple-pages-pwa/src/pages/b.vue
- examples/multiple-pages-pwa/src/pages/nested/deep/a.vue
- examples/multiple-pages-with-store/src/pages/b.vue
- examples/multiple-pages/src/pages/b.vue
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/client/index.ts
- src/client/single-page.ts
- src/types.ts
This PR also includes:
- update `pnpm` to 10.6.5
- update `unbuild` to `3.5.0`
- fix eslint config => moved to `.mjs` replacing `module.exports` with `export default` + `await`
- remove all `unhead children` style usages using `textContent` instead: `unhead v2`  deprecated `children` in favor of `innerHTML` and `textContent` for `script`and `style` tags respectively.
~~Looks like `unhead` doesn't export `VueHeadClient` type/interface  from `@unhead/vue/client` and so we need to use `ReturnType<typeof createHead>` in our client types.~~ `VueHeadClient`  can be imported from `@unhead/vue`
The tests are fine, running all the examples also fine, I need to check it with `vitesse`.
closes #439
> feat!: use `unhead v2`

- src/client/index.ts
- src/client/single-page.ts
Treeshake hydration support as the feature (default to `false` and using `createSSRApp`) is not currently tree shaken and leads to extra 5Kb in client bundle size (check screenshots).
Rollup wasn't able to tree-shake because of :
1) Default options (`= {}`)
2) Default + destructure of treeshake value (`= false`)
The difference is mainly (if not only) explained by `createSSRApp` import from `vue` that was previously shipped even if not used on client (`createSSRApp` is used on client when `hydration` is `true`)
> fix(client): treeshake hydration

- examples/multiple-pages-with-store/package.json
- examples/multiple-pages-with-store/vite.config.ts
- package.json
- src/node/build.ts
- test/asset.test.ts
This PR just uses the original `join` as suggested in the linked issue, adding a test using `examples/multiple-pages-with-store`.
resolves #454
> fix(dir-styles): use `join` instead `resolve` when using nested dir style
